version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_nlp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jee_db
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nlpapp:
    build: .
    container_name: nlp_annotation_app
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

volumes:
  db_data:
